### ISSUE TITLE
Sports Data LLC Name Change?

### ISSUE THREAD

**Issue by TheKidCoder** [RLovelett/sports_data_api#44]
Did Sports Data LLC rebrand itself as SportsRadar? Somewhat confused as to if this gem is compatible with: http://developer.sportradar.us

**Comment by RLovelett** [comment]
It does look like they have rebranded. I'm going to re-run all the tests against their API. My guess is that it'll work just fine.

**Comment by RLovelett** [comment]
I got an email from them 23 April.

> From: sales@sportsdatallc.com SportsData 
> To:  
> Date: Thu, 23 Apr 2015 11:27:15 -0400 
> Subject: SportsData News: Our New Name and Official NFL Partnership! 

> Partners and Friends,

> Monday marked an exciting day in our company's growth and evolution, as we officially rebrand as Sportradar US, while announcing our [biggest league partnership to date](http://r20.rs6.net/tn.jsp?f=001gTUMy_E2Al6Yj5FdyueksYwzbOx-BZ7XINUTcI0beJzPWYZzCQhHI9DmTECEPL8HL2hjftBt7TwmyELfnnrr_77bYTXKtGTVPgUrhXzU-tnRlkAuKk3WXOpWNstTY_4Ykpkh2cPdyxDw7OtnyAVN7zG83ipc4-PSdc25sInPe1y2svYbX_CH0375GnBmkqCN45qW9BIicbrI4Bl8dsf7cEa8CpOfItOddNSxGVtbm0QqfjQ7zRwaCLVmCdJ869AVyzl9YzUoR21JvY2JyMiJ5NWCvCXhPfPiVXB9ppbxawz7IhyYM0nhaTIU8ki5y4a1Oj1nVmiRzkw=&c=sFWSDUnL3w3r_6DaiNbWSmhz2GEyaixqRnZTkfAieyUAE9FCmtfFmA==&ch=_hoXSJeP8Ya3rVRv_YutowCzIravls4EaBIW54lmpmIZjQUVJKVrxg==) - a four year exclusive deal with the National Football League beginning this fall
2015!

> This rebranding is far more than a name change - it's the next logical step in the evolution of Sportradar and SportsData as one entity, and is great news for both our current and future clients. Sportradar US will continue to build on SportsData's legacy of serving as a true technology partner to our clients and league partners, which we take pride in and believe separates us from our industry competitors.

> As you may know, Sportradar is the world's largest data provider, with 5,000 data entry analysts covering 40 sports and nearly 300,000 annual events. For the past eighteen months, we have been in close collaboration with Sportradar senior executives to ensure that the best of both organizations are represented in the services that
we offer to the marketplace. We're confident that our planning will ensure that Sportradar US remains the fastest-growing sports data provider in the U.S. The NFL selecting us as their official data provider truly validates the power of the technology platform we have built.

> To support our ambitious plans, we have opened a new, 20,000 square foot North American Headquarters in downtown Minneapolis for our data collection, processing, and monitoring operations. This state-of-the-art facility will allow our live data analysts to capture more sports and deeper data sets, and to deliver data faster than ever before.

> We will continue to announce more exciting developments in the coming months to support our mission to drive innovation in sports. Look for news soon on a relaunched website, new APIs, and additional industry partners.

> As always, thank you for your support and we look forward to continuing to serve your needs in the seasons and years to come!

> Sincerely,

> Rob Phythian,

> GM, Sportradar US

**Comment by RLovelett** [comment]
I re-ran all the tests on the suite and everything passed. There were a couple of brittle tests (probably from me) that I discovered as part of re-running the suite. I'll fix those as a separate issue.

For now, I'm going to say that everything is working to spec. I might even update the README to use the new name so that it is clear that there was a name change. Other than that I am going to call this issue closed. If you notice something wrong go ahead and file a separate issue for those.

Thanks @TheKidCoder
