### ISSUE TITLE
Gem ownership

### ISSUE THREAD

**Issue by trevorrjohn** [RLovelett/sports_data_api#63]
Hey @RLovelett can you add me to the gem ownership so that I can publish new versions going forward? See http://guides.rubygems.org/command-reference/#gem-owner

**Comment by trevorrjohn** [comment]
@RLovelett  any thoughts on this?

**Comment by RLovelett** [comment]
I'll do that today.

**Comment by RLovelett** [comment]
```
$ gem owner --add "trevor@john.tj" sports_data_api
Adding trevor@john.tj: Owner could not be found.
```

`¯\_(ツ)_/¯`

What email should I use?

**Comment by trevorrjohn** [comment]
trevorrjohn@gmail.com

On Fri, Feb 3, 2017 at 8:40 AM Ryan Lovelett <notifications@github.com>
wrote:

$ gem owner --add "trevor@john.tj" sports_data_api
Adding trevor@john.tj: Owner could not be found.

¯\_(ツ)_/¯

What email should I use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RLovelett/sports_data_api/issues/63#issuecomment-277248765>,
or mute the thread

**Comment by RLovelett** [comment]
```
$ gem owner sports_data_api --add "trevorrjohn@gmail.com"
Owner added successfully.
Owners for gem: sports_data_api
- trevorrjohn
- ryan@lovelett.me
```

✅
